on:
  push:
    branches:
      - main
jobs:
  update-changelog:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: One More Time
        uses: jmm-podium/one-more-time@main
        id: omt
        with:
          github-token: ${{ secrets.PAT_GITHUB }}
          github-repository:  ${{ github.repository }}
          github-sha: ${{ github.token }}

      - name: Get the result
        run: echo "The result was ${{ steps.omt.outputs.result }}"