on:
  push:
    branches:
      - main
jobs:
  update-changelog:
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: One More Time
        uses: jmm-podium/one-more-time@main
        id: omt
        with:
          github-token: "token"

      - name: Get the result
        run: echo "The result was ${{ steps.omt.outputs.result }}"