on: [push]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ github.head_ref }}"
      - name: Checkout
        uses: actions/checkout@v2

      - name: One More Time
        uses: jmm-podium/one-more-time@main
        id: omt
        with:
          github-token: "token"

      - name: Get the result
        run: echo "The result was ${{ steps.omt.outputs.result }}"