on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Read .SEMVER file
        id: getversion
        run: echo "::set-output name=version::$(cat .SEMVER)"

      - name: Update Changelog
        uses: podium-education/kraken@v0.4.1-tagupdate
        id: kraken
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-repository:  ${{ github.repository }}
          github-sha: ${{ github.sha }}
          version: ${{ steps.getversion.outputs.version }}
          git-tag-mode: on
          git-tag-format: v<version>

      - name: Get the result
        run: echo "The result was ${{ steps.kraken.outputs.result }}"